- name: "Prompt for email"
  pause:
    prompt: "Enter email"
  register: email

- name: "Prompt for password"
  pause:
    prompt: "Enter email password"
  register: email_password

- name: "Check default terminal"
  shell: hostname
  register: current_hostname
  changed_when: False

- name: "Setup sSMTP"
  template:
    src: templates/ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: mail
    mode: 0644
  become: yes
  become_user: root
