#+TITLE: README for conf
#+AUTHOR: johsim

Instructions on how to setup a new environment and how to modify certain variables.
* General setup
To setup the environment on a new platform, please follow these steps (Tested on XUbuntu 15.04, 15.10).
** Setup Git repository
Install Git and clone this repository.
#+BEGIN_SRC 
sudo apt-get install git
git clone https://github.com/johsim/joh-conf
#+END_SRC

If the network is behind a HTTP-proxy, try specifying the default one:
#+BEGIN_SRC sh
git config --global http.proxy http://proxy1:80
#+END_SRC

To configure local variables:
#+BEGIN_SRC sh
git config --global user.name "Joh Sim"
git config --global user.email johsim@example.com
#+END_SRC

** Setup local configuration files
Copy the ~.bashrc~ to the home directory
#+BEGIN_SRC sh
cp ~/joh-conf/conf/.bashrc ~/
#+END_SRC

Install Emacs
#+BEGIN_SRC sh
sudo apt-get install emacs24 emacs24-el emacs24-common-non-dfsg
#+END_SRC

The emacs_conf.el file can be used without moving it away from the git repository. To do this, copy the init file to the emacs.d directory:
#+BEGIN_SRC sh
cp ~/joh-conf/conf/init.el ~/emacs.d/
#+END_SRC

** Install preferable software
*** Quicktile
Quicktile implements keyboard-driven Window Tiling, and can be retrieved from: https://github.com/ssokolow/quicktile

 * Install the required dependencies and follow the instructions.
 * Open the ./config/quicktile.config and change ModMask to <Mod4> (Windows button)

*** Terminator
Install terminator through apt-get:
#+BEGIN_SRC bash
sudo apt-get install terminator
#+END_SRC

Go to Preferred Applications > Utilites > Terminal Emulator and choose terminator.

To fix the incompability bug with Quicktile, go to Preferences and unselect 'Window geometry hints'.

To use the stored configuration, copy ~\~/joh-conf/conf/terminator/config~ to ~\~/.config/terminator/~.

*** LaTeX
To be able to generate PDF files from LaTeX and utilize other features, install:
#+BEGIN_SRC sh
sudo apt-get install texlive
#+END_SRC

*** ssmtp
sstmp can be used to send mail via CLI, and is a simple MTA.
#+BEGIN_SRC sh
sudo apt-get install ssmtp
#+END_SRC

The configuration can be done via:

#+BEGIN_SRC sh
sudo emacs -nw /etc/ssmtp/ssmtp.conf
#+END_SRC

The configuration should look something like this:
#+BEGIN_SRC sh
# Config file for sSMTP sendmail
#
# The person who gets all mail for userids < 1000
# Make this empty to disable rewriting.
#root=postmaster
root=MyEmailAddress@gmail.com

# The place where the mail goes. The actual machine name is required no
# MX records are consulted. Commonly mailhosts are named mail.domain.com
#mailhub=mail
mailhub=smtp.gmail.com:587
# Where will the mail seem to come from?
#rewriteDomain=
rewriteDomain=gmail.com

# The full hostname
#hostname=MyMediaServer.home
hostname=MyEmailAddress@gmail.com

# Are users allowed to set their own From: address?
# YES - Allow the user to specify their own From: address
# NO - Use the system generated From: address
FromLineOverride=YES
AuthUser=MyEmailAddress@gmail.com
AuthPass=MyPassword
UseTLS=YES
UseSTARTTLS=YES
TLS_CA_File=/etc/ssl/certs/ca-certificates.crt
#+END_SRC

*** autojump
Install autojump through apt-get:
#+BEGIN_SRC bash
sudo apt-get install autojump
#+END_SRC

Use with
#+BEGIN_SRC bash
j <start-of-path>
#+END_SRC

*** thefuck
Autocorrection for terminal input. Follow instructions found on:
https://github.com/nvbn/thefuck

* Emacs
** Update default packages
The default packages that Emacs will use are specified in the variable ~package-list~ found in ~emacs_conf.el~. If any new packages have been installed and are to be added to the default list, please follow these steps:

1. List all currently installed packages with: ~C-h v package-activated-list~

2. Copy the array to the ~package-list~ variable in ~emacs_conf.el~.

3. Restart emacs. 
